client/.eslintrc.json, client/package-lock.json, client/package.json, client/src/App.tsx, client/src/components/Header.tsx, client/src/index.tsx, client/src/pages/club/club/CreateClub.tsx, client/src/pages/club/club/EditClub.tsx, client/src/pages/club/intro/ClubIntro.tsx, client/src/pages/club/manage/ClubManage.tsx, client/src/pages/club/manage/MemberManage.tsx, client/src/pages/club/match/ClubSchedule.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/EditMatch.tsx, client/src/pages/club/match/MatchDetail.tsx, client/src/pages/club/member/ClubMember.tsx, client/src/pages/club/member/MemberRecord.tsx, client/src/pages/club/setting/ClubSetting.tsx, client/src/pages/club/setting/MemberSetting.tsx, client/src/pages/home/Home.tsx, client/src/pages/home/Intro.tsx, client/src/pages/user/EditProfile.tsx, client/src/pages/user/Login.tsx, client/src/pages/user/MyPage.tsx, client/src/pages/user/Register.tsx, client/src/pages/user/SetNickname.tsx
=> ✨feat : 페이지 라우터 PR

server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/repository/CandidateRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/service/CandidateService.java
Reverts codestates-seb/seb42_main_018#28
=> Revert "🚚 rename : Comment Directory"

client/src/GlobalStyles.ts, client/src/components/Header.tsx, client/src/components/S_Container.ts, client/src/pages/home/Intro.tsx
1. 글로벌 스타일 설정
2. 헤더 임시 설정
3. 기본 컨테이너 설정
+) 루트 컬러 재확인 필요
=> 🎨style: 글로벌스타일 설정

server/src/main/java/com/codestates/mainproject/group018/somojeon/category/controller/CategoryController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/category/service/CategoryService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/enums/ClubMemberStatus.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/enums/ClubRole.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/enums/ClubStatus.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java
* 요구사항 ID : 
* Issue No. : 
- 넘버링 등 편한 마크다운 방식으로 작성해주세요
- 필요한 경우 상세 내용 설명
* 변경 이유: 
* 필요한 경우 작성
=> ♻️ refactor : "Club 컨트롤러 수정"

client/public/index.html, client/src/components/kakao/KakaoMap.css, client/src/components/kakao/KakaoMapSearch.tsx, client/src/components/kakao/KakaoMapView.tsx, client/src/components/match/ScheduleCard.tsx, client/src/pages/club/match/ClubSchedule.tsx, client/src/pages/club/match/CreateMatch.tsx
* 요구사항 ID : CLUB-SCHEDULE-CREATE
* Issue No. :  #38 
- 매니저/리더 권한의 경기 생성 시 장소 검색 후 설정 -> 멤버들이 해당 장소 확인 가능
* Typescript 컨벤션 결정 후 적용 완료 예정
=> [FE] ✨feat : 경기등록 카카오맵API 적용

client/src/components/TabMenu.tsx, client/src/components/UI/S_Container.ts, client/src/components/UI/S_Modal, client/src/components/UI/S_Select.tsx, client/src/components/UI/S_Tag.ts, client/src/pages/club/member/ClubMember.tsx, client/src/pages/club/member/ClubMemberList.tsx, client/src/pages/club/member/MemberNav.tsx, client/src/pages/club/member/MemberRecord.tsx, client/src/pages/club/member/MemberRecordList.tsx, client/src/pages/club/member/MemberRecordTitle.tsx, client/src/pages/home/Intro.tsx
* 요구사항 ID : 
* Issue No. : close #54 
- 스타일 일부 수정 및 업데이트
- 소모임 내 탭 메뉴 생성
- 소모임 멤버 페이지 생성
- 하드코딩으로 처리되어 있으며 데이터 받아오는 부분 추후 업데이트
=> [FE]✨feat: 스타일 업데이트/소모임 멤버 목록 생성

client/src/API_TEST.tsx, client/src/App.tsx, client/src/components/UI/S_Button.tsx, client/src/pages/user/Login.tsx
* 요구사항 ID : 
* Issue No. : #18 
* api 테스트: get 요청
=> [FE] ✅test : 서버와 통신 테스트 - get 요청

client/src/API_TEST.tsx, client/src/pages/user/Login.tsx
* 요구사항 ID : USER-LOGIN
* Issue No. : #18 
* 로그인 페이지에 일반회원가입 버튼 추가
* sample data POST 요청
=> ✅test : 로그인 페이지에 일반회원가입 버튼 추가 (post 요청)

server/src/main/java/com/codestates/mainproject/group018/somojeon/category/controller/CategoryController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/category/dto/CategoryDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/category/entity/Category.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/category/mapper/CategoryMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/category/service/CategoryService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/ClubTag.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/ClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/ClubRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/ClubTagRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/dto/CategoryResponseDtos.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/dto/ClubCategoryResponseDtos.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/tag/dto/TagDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/tag/entity/Tag.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/tag/mapper/TagMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/tag/repository/TagRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/tag/service/TagService.java
* 요구사항 ID : 
* Issue No. : 
- [] Feature 
로직변경, 소모임 생성, 수정, 조회, 삭제 api테스트 할 수 있게 리팩터링
* 변경 이유:
* 필요한 경우 작성
=> [BE} ♻️ refactor : "카테고리별 소모임 조회 로직 추가, Club 서비스 로직 변경, Club/Tag 다대다 매핑 엔티티 추가"

client/src/pages/user/Login.tsx
* 요구사항 ID : USER-LOGIN-KAKAO
* Issue No. : #65 
* 변경 부분: 카카오톡 로그인 버튼 클릭시 axios get 요청에서 url 리다이렉션으로 코드 수정
=> [FE] ✅ fix : 카카오 로그인 api url로 리다이렉션하게 수정

client/src/API_TEST.tsx
* 요구사항 ID : 
* Issue No. : #18 
* 이미지 파일 업로드하여 서버에 post 요청 테스트를 위한 코드
=> [FE] 🐛 fix : 이미지 파일 서버에 post 요청

.idea/workspace.xml, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/controller/CandidateController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/comment/controller/CommentController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/record/controller/RecordController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/controller/TeamController.java, server/src/main/resources/application.yml
* 요구사항 ID : 
* Issue No. : 
* refactor constructor
=> ♻️ refactor : controller constructor refactor

server/src/main/java/com/codestates/mainproject/group018/somojeon/category/controller/CategoryController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/category/service/CategoryService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/exception/ExceptionCode.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/controller/ImageController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/service/ImageService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/join/controller/JoinController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/join/dto/JoinDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/join/service/JoinService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/entity/User.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/utils/dummy/InsertDummyUserDatabyService.java
* 요구사항 ID : 
* Issue No. : 
Club api주소 변경
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "Club api주소 변경" 

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java
* 요구사항 ID : 
* Issue No. : 
- 넘버링 등 편한 마크다운 방식으로 작성해주세요
- 필요한 경우 상세 내용 설명
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "Club CrossOrigin 애너테이션추가"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/ClubTag.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java
* 요구사항 ID : 
* Issue No. : 
소모임 이름 생성시 이름에 제한 걸어놓은 것 해제
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "ClubDto 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java
* 요구사항 ID : 
* Issue No. : 
소모임 content Length 수정
* 변경 이유:
* 필요한 경우 작성
=> ♻️ refactor : "소모임 content Length 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java
* 요구사항 ID : 
* Issue No. : 
소모임 content Length 및 띄어쓰기 수정
* 변경 이유:
* 필요한 경우 작성
=> ♻️ refactor : "소모임 content Length 및 띄어쓰기 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java
* 요구사항 ID : 
* Issue No. : 
소모임 content Length 및 띄어쓰기 수정 재업
* 변경 이유:
* 필요한 경우 작성
=> ♻️ refactor : "소모임 content Length 및 띄어쓰기 수정 재업"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java
* 요구사항 ID : 
* Issue No. : 
소모임 content Length 및 띄어쓰기 재수정이요 ㅠㅠ
* 변경 이유:
* 필요한 경우 작성
=> ♻️ refactor : "소모임 content Length 및 띄어쓰기 재수정이요 ㅠㅠ"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/utils/dummy/InsertDummyUserDatabyService.java
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "CrossOrigin에 버셀 사이트 추가"
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "CrossOrigin에 버셀 사이트 추가"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "club엔티티 원복"
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "club엔티티 원복"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "club생성 content길이 마지막 수정 테스트 완료"
* 변경 이유:
* 필요한 경우 작성
=> ♻️ refactor : "club생성 content길이 마지막 수정 테스트 완료"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java
* 요구사항 ID : 
* Issue No. : 
"club생성시 NPE나서 일단 clubService image쪽 코드 주석처리"
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "club생성시 NPE나서 일단 clubService image쪽 코드 주석처리"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "club 엔티티 TEXT 추가"
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "club 엔티티 TEXT 추가"

client/src/API_TEST.tsx
* 요구사항 ID : 
* Issue No. : 
*request header의 content type 삭제
=> 🐛 fix : content-type 삭제

server/src/main/java/com/codestates/mainproject/group018/somojeon/images/controller/ImageController.java
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "image 컨트롤러 수정"
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "image 컨트롤러 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/dto/ScheduleDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/entity/Schedule.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/entity/UserTeam.java
* 요구사항 ID : 
* Issue No. : 
- front data 전달을 위해 post, patch, response 수정
- clubDto NoArgsConstructor update
=> ♻️ refactor : schedule request/response 부분 update

server/src/main/java/com/codestates/mainproject/group018/somojeon/images/service/ImageService.java, server/src/main/resources/application-dummy.yml, server/src/main/resources/application-server.yml, server/src/main/resources/application.yml
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "yml 파일 수정, 이미지 url 수정"
* 변경 이유:
* 필요한 경우 작성
=> ♻️ refactor : "yml 파일 수정, 이미지 url 수정"

.idea/workspace.xml, server/src/main/java/com/codestates/mainproject/group018/somojeon/auth/filter/JwtVerificationFilter.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/auth/handler/UserAuthenticationSuccessHandler.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/auth/utils/CustomAuthorityUtils.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/config/SecurityConfiguration.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/dto/UserDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/mapper/UserMapper.java
* 요구사항 ID : 
* Issue No. : 
- 유저 정보에 이미지 URI가 추가되었습니다.
- 카카오톡 회원가입 로직의 버그를 수정했습니다.
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🐛 fix  카카오톡 회원가입 버그수정 && ✨ feat 유저 정보에 이미지 추가

client/src/components/match/AddMemberPopUp.tsx, client/src/components/match/RecordCard.tsx, client/src/components/match/TeamCard.tsx, client/src/components/setting/MemberUserCard.tsx, client/src/components/setting/MemberWaitingCard.tsx, client/src/pages/club/match/ClubSchedule.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/EditMatch.tsx, client/src/pages/club/match/MatchDetail.tsx, client/src/pages/club/match/_pastMatch.tsx, client/src/pages/club/setting/ClubSetting.tsx, client/src/pages/club/setting/MemberSetting.tsx, client/src/pages/club/setting/_bannedMember.tsx, client/src/pages/club/setting/_totalMember.tsx, client/src/pages/club/setting/_waitingMember.tsx, client/src/pages/user/Register.tsx
* 요구사항 ID : 
* Issue No. : 
* 멤버세팅 -> 가입대기유저, 전체유저목록 각 카드컴포넌트 생성 후 적용(API호출 부분 미구현)
=> [FE]🐛fix : 멤버세팅 추가구현 + 🔧update: 경기생성/수정 변수명 수정

.idea/workspace.xml, server/src/main/java/com/codestates/mainproject/group018/somojeon/exception/ExceptionAdvice.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/exception/ExceptionCode.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/dto/UserDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/utils/Identifier.java
* 요구사항 ID : 
* Issue No. : 
- 에러 핸들러에 커스텀 코드 적용가능하게 로직 추가
- 회원가입 시  엑세스 토큰이 없는 경우에 NPE가 발생하던 버그 수정
* 변경 이유:
* 필요한 경우 작성
=> [BE]  ✨ feat 이메일 중복에 1000번 ExceptionCode 할당 && 🐛 fix 회원가입 버그 수정

client/src/pages/club/match/ClubSchedule.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 부분: ClubSchedule.tsx 상단 탭메뉴 추가
=> [FE]🔧 update: 소모임스케쥴 탭 추가

client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/setting/_waitingMember.tsx
=> [FE] 🔧 update:  가입신청유저정보에 맞게 type 변경/경기일정생성 API구현업데이트

client/src/pages/club/match/CreateMatch.tsx
=> 🔧 update: 경기일정생성 API 반영 업데이트

client/src/pages/club/match/CreateMatch.tsx
=> 🐛 fix: 경기등록 API수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/UserClub.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> 🔧 update :  "Userclub 엔티티 Intger -> int 로 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java
* 요구사항 ID : 
* Issue No. : 
- cors로 인한 annotation 추가
=> [BE] 🔧 update : schedule cors 에러 annotation 수정

client/src/components/login/_inputEmail.tsx, client/src/components/login/_inputNickname.tsx, client/src/components/login/_inputPassword.tsx, client/src/pages/user/Login.tsx, client/src/pages/user/Register.tsx
* 요구사항 ID : 
* Issue No. : 
* 로그인, 회원가입 페이지의 공통 input 요소 sub-component로 분리
* 회원정보 수정 페이지에서도 공통으로 사용할 수 있음
=> ♻️refactor : 공통 input 컴포넌트 작성 및 적용

server/src/main/java/com/codestates/mainproject/group018/somojeon/comment/entity/Comment.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/record/entity/Record.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/entity/TeamRecord.java
* 요구사항 ID : 
* Issue No. : 
- Many To One Entity fetch = FetchType.LAZY 로 모두 수정
=> [BE] 🔧 update : entity fetch 설정 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/record/entity/Record.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/entity/Schedule.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/entity/Team.java
* 요구사항 ID : 
* Issue No. : 
- entity cascade 설정
=> [BE] 🔧 update : entity cascade 설정 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/UserClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/UserClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/UserClub.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/UserClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/UserClubRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/mapper/UserMapper.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update :  "소모임 활동 멤버 목록 조회 업데이트"

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/entity/Team.java
* 요구사항 ID : 
* Issue No. : 
- schedule service 기능 복구
=> [BE] 🔧 update : schedule service 설정 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/UserClub.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> 🔧 update :  "club 엔티티 마이너한 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/dto/ScheduleDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java
* 요구사항 ID : 
* Issue No. : 
- schedule 변수명 수정
=> 🔧 update : schedule 변수명 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/UserClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/UserClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/UserClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/UserClubRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/dto/UserDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/mapper/UserMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
🔧 update :  "UserClub 에 userInfo 넣어주는 매퍼작업 완료"
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update :  "UserClub 에 userInfo 넣어주는 매퍼작업 완료"

client/src/components/setting/MemberWaitingCard.tsx, client/src/pages/club/setting/_waitingMember.tsx
* 요구사항 ID : 
* Issue No. : 
* 가입신청 전체조회, 승인 구현
=> [FE]🔧 update: 소모임가입신청 API  업데이트

client/src/pages/club/setting/_waitingMember.tsx
=> [KE]🐛 fix: 소모임가입신청 수정

client/src/pages/club/setting/_waitingMember.tsx
=> [KE]🐛 fix: 소모임가입신청 API  수정

client/src/components/setting/MemberWaitingCard.tsx, client/src/pages/club/setting/_waitingMember.tsx
=> [KE]🔧 update: 소모임가입신청/거절 후 목록 제거 구현

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/dto/ScheduleDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java
* 요구사항 ID : 
* Issue No. : 
- schedule service 수정
=> [BE] 🔧 update : schedule service 수정

client/src/components/club/member/recordList.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [FE] 버셀배포용 임시 커밋

client/src/components/setting/MemberWaitingCard.tsx, client/src/pages/club/setting/_waitingMember.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
=> [KE]🐛 fix: 가입승인 PENDING상태 유저만 보이게 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/UserClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/UserClubMapper.java
* 요구사항 ID : 
* Issue No. : 
로그인시 필요한 정보가 userClubId가 아니고 club아이디가 필요하다고해서 수정했습니다.
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update  :  "UserClubResponse에 clubId 추가 "

client/src/pages/club/setting/_waitingMember.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 부분: 가입 승인 후 PENDING 유저만 보이게 수정
=> 🐛 fix: 가입승인 PENDING상태 유저만 보이게 수정

client/src/pages/club/match/ClubSchedule.tsx, client/src/pages/club/match/MatchDetail.tsx, client/src/pages/club/setting/_waitingMember.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 부분: 모든 경기일정 조회 수정, PENDING 유저 승인처리시 목록 리렌더링
=> [FE]🐛 fix: 모든경기일정조회 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/dto/ScheduleDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java
* 요구사항 ID : 
* Issue No. : 
- schedule response scheduleId 다시 추가
=> [BE] 🔧 update : schedule response 부분 수정

.idea/workspace.xml, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java
* 요구사항 ID : 
* Issue No. : 
- 변수 부분 일치화
=> [BE] 🔧 update : schedule service 변수 부분 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/dto/ScheduleDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/mapper/TeamMapper.java
* 요구사항 ID : 
* Issue No. : 
- schedule mapper 수정
=> [BE] 🔧 update : schedule mapper 부분 수정

client/src/pages/club/match/MatchDetail.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 부분: 카카오맵 지도 경도/위도 수정
=> [FE]🐛 fix: 경기상세 지도 경도/위도 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/ClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "isPrivate -> isSecret 으로 바꿈 (private 는 javascript 예약어)"
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "isPrivate -> isSecret 으로 바꿈 (private 는 javascript 예약어)"

server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/controller/CandidateController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/dto/CandidateDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/service/CandidateService.java
* 요구사항 ID : 
* Issue No. : 
- candidate api 수정
=> [BE] 🔧 update : candidate 부분 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/ClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/controller/ImageController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/entity/Images.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/service/ImageService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/utils/dummy/InsertClubDummyData.java
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "소모임 수정 가능하게 바꿈. 소모임 생성시 defaultClubImage 들어감."
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "소모임 수정 가능하게 바꿈. 소모임 생성시 defaultClubImage 들어감."

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/dto/UserDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
♻️ refactor : "유저 생성시 디폴트 이미지 나오게 바꿈"
* 변경 이유:
* 필요한 경우 작성
=> [BE] ♻️ refactor : "유저 생성시 디폴트 이미지 나오게 바꿈"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=>  🔧update: "Userclub service 수정."

server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=>  update: "회원가입 안되는 것 디폴트 이미지 때문이라 일단 주석처리"

server/src/main/java/com/codestates/mainproject/group018/somojeon/user/dto/UserDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/mapper/UserMapper.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=>  update: "소모임 멤버 조회할 때 userId 같이 넘겨주게 DTO MAPPER 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/controller/CandidateController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/dto/CandidateDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/entity/Candidate.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/mapper/CandidateMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/service/CandidateService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/UserClubRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/dto/ScheduleDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java
* 요구사항 ID : 
* Issue No. : 
- schedule 참석 및 불참에 대한 기능 구현 추가
=> [BE] ✨ feat : attend, absent 관련 로직 구현

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/UserClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/UserClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/ClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/UserClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/UserClubRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=>  [BE] update: "소모임 멤버 조회할 때 멤버 활동 상태 조회 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/dto/UserDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/mapper/UserMapper.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=>  [BE] update: "소모임 멤버 조회 DTO 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/repository/CandidateRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java
* 요구사항 ID : 
* Issue No. : 
- 중복 저장 되는 부분 처리 및 id 찾아서 수정하게 구현
=> [BE] 🔧 update : 참석 불참 기능 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java
* 요구사항 ID : 
* Issue No. : 
- schedule candidate 부분 수정
=> [BE] 🔧 update : candidate 참석 / 불참 부분 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/UserClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/ClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/UserClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/controller/ImageController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/service/ImageService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/dto/UserDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/entity/User.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/mapper/UserMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java, server/src/main/resources/application.yml
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE🔧 update: "이미지 수정부분 코드수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/service/ImageService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update: "클럽 이미지 관련건 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/controller/CandidateController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/dto/CandidateDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/mapper/CandidateMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/repository/CandidateRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/service/CandidateService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/dto/ScheduleDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update : candidate 조회 부분 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/UserClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/controller/ImageController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/entity/Images.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/service/ImageService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/dto/UserDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/entity/User.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/mapper/UserMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
🔧 update: "프로필 이미지, 클럽 이미지 수정 로컬테스트 완료 진짜 끝..."
유저서비스, 컨트롤러, dto, mapper 전부 수정. 기본코드는 남겨뒀습니다. -> 제훈
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update: "프로필 이미지, 클럽 이미지 수정 로컬테스트 완료 진짜 끝..."

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=>  [BE] 🔧update: "userClub cascade 추가"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/ClubTag.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/UserClub.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/utils/dummy/InsertClubDummyData.java
* 요구사항 ID : 
* Issue No. : 
🔧 update : "엔티티 GenerationType 수정"
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update : "엔티티 GenerationType 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/ClubTag.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/UserClub.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] update : "엔티티 GenerationType 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/UserClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/UserClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/UserClubRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java, server/src/main/resources/application-dummy.yml, server/src/main/resources/application.yml
* 요구사항 ID : 
* Issue No. : 
update: "클럽 아이디 안에 있는 멤버 목록만 조회하도록 수정"
* 변경 이유:
* 필요한 경우 작성
=> [BE]  update: "클럽 아이디 안에 있는 멤버 목록만 조회하도록 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/mapper/CandidateMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/dto/ScheduleDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/entity/Schedule.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/mapper/ScheduleMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/mapper/TeamMapper.java
* 요구사항 ID : 
* Issue No. : 
- 전적에 따른 userClub 값들 추가 되게 구현
- schedule put 로직 부분 수정
=> [BE] 🔧 update : schedule service 부분 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update : schedule service 부분 재수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/UserClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/enums/ClubMemberStatus.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/UserClubRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
update: "소모임 관련 권한같은 것들 추가 및 수정"
update: "defaultImage 명 변경"
* 변경 이유:
* 필요한 경우 작성
=>  [BE] update: "소모임 관련 권한같은 것들 추가 및 수정"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/UserClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/ClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/UserClubService.java, server/src/main/resources/application-dummy.yml, server/src/main/resources/application.yml
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> ✨ feat: "소모임 이용 정지 / 해제 로직 추가"

server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/entity/Candidate.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update : enum 값 영어로 수정

client/src/components/UI/S_Button.tsx, client/src/components/match/ScheduleCard.tsx, client/src/components/setting/MemberWaitingCard.tsx, client/src/pages/club/match/ClubSchedule.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/EditMatch.tsx, client/src/pages/club/match/MatchDetail.tsx, client/src/pages/club/match/_pastMatch.tsx, client/src/pages/club/match/_scheduledMatch.tsx, client/src/pages/club/setting/_totalMember.tsx, client/src/pages/club/setting/_waitingMember.tsx, client/src/util/api.ts
* 요구사항 ID : 
* Issue No. : 
소모임 멤버가 소모임 일정에 대한 참가, 불참 버튼 클릭으로 스케쥴 참여 여부 반영.
=> [FE]🐛 fix: 경기상세보기 수정/참가,불참 구현

server/src/main/java/com/codestates/mainproject/group018/somojeon/record/dto/RecordDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/record/entity/Record.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/dto/TeamDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/entity/Team.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/mapper/TeamMapper.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] 🔧 update : team, record 관련 수정 schedule service 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/repository/ClubRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java
* 요구사항 ID : 
* Issue No. : 
✨ feat: "내가 가입신청중인 소모임 리스트 조회 추가 (마이페이지)"
* 변경 이유:
* 필요한 경우 작성
=> [BE] ✨ feat: "내가 가입신청중인 소모임 리스트 조회 추가 (마이페이지)"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/images/service/ImageService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=>  [BE] update: "프로필 / 소모임 수정 업데이트"

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/exception/ExceptionCode.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
update: "소모임수정, 프로필수정 쓸데없이 주입받은 엔티티 삭제"
ExceptionCode 번호별로 정리함
* 변경 이유:
* 필요한 경우 작성
=> [BE]  update: "쓸데없이 주입받은 엔티티 삭제"

client/src/pages/club/intro/ClubIntro.tsx, client/src/pages/user/Register.tsx, client/src/pages/user/_receiveOauth2.tsx, client/src/store/store.ts, client/src/util/api.ts, client/src/util/authorization/useLoginRequestLogic.ts, client/src/util/authorization/useLogoutRequestLogic.ts
* 요구사항 ID : 
* Issue No. : 
* 소모임 소개 페이지 이미지 영역 크기에 맞춰서 이미지 파일 보여주기
* jwt 토큰 갱신 작업 여전히 미궁 속...
=> [FE] 💄design : 소모임 소개 페이지 프로필 이미지 사이즈 레이아웃 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/ClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java
* 요구사항 ID : 
* Issue No. : 
update: "데이터 이름 tagList 로 모두 수정"
* 변경 이유:
* 필요한 경우 작성
=> [BE] update: "데이터 이름 tagList 로 모두 수정"

.idea/workspace.xml, server/src/main/java/com/codestates/mainproject/group018/somojeon/auth/handler/OAuth2UserSuccessHandler.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/config/WebConfig.java, server/src/main/resources/application-dummy.yml
* 요구사항 ID : 
* Issue No. : 
* 카카오 로그인 시 Origin에 따라 리다이렉팅을 다르게 하는 분기를 추가했습니다.
* 변경 이유:
* 필요한 경우 작성
=> ✨ feat Origin에 따른 리다이렉팅 분기 설정

client/src/components/MyPage/ClubListSetting.tsx, client/src/components/home/home/ClubList.tsx, client/src/components/home/home/MainContents.tsx, client/src/pages/club/club/CreateClub.tsx, client/src/pages/club/club/EditClub.tsx, client/src/pages/club/club/_createLocal.tsx, client/src/pages/club/club/_createTag.tsx, client/src/pages/club/intro/ClubIntro.tsx, client/src/types/index.ts
* 요구사항 ID : 
* Issue No. : 
* 변경 부분: ClubData 타입 관련 tagResponseDto -> tagList로 일괄 변경 적용
* 변경 이유: 서버에서 보내주는 데이터 변경
=> [FE] 🔧update : 클럽 데이터 key name 변경 반영

client/src/pages/club/club/EditClub.tsx, client/src/pages/club/club/_createLocal.tsx, client/src/pages/club/intro/ClubIntro.tsx
* 요구사항 ID : CLUB-EDIT
* Issue No. : 
* 소모임 정보 수정 페이지 버그 수정 중 (BE와 협의 중)
* 현재 이미지 등록 없이 기존 이미지가 그대로인 상태에서 patch 요청 보내면 500번 에러 뜨고 있음
=> [FE] 🐛fix : 소모임 수정 페이지 지역 정보 관련 버그 임시 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java
* 요구사항 ID : 
* Issue No. : 
update: "소모임 수정 clubImage null 일때 등록안함"
* 변경 이유:
* 필요한 경우 작성
=>  update: "소모임 수정 clubImage null 일때 등록안함"

server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
update: "프로필 수정 profileImage null 일때 등록안함"
* 변경 이유:
* 필요한 경우 작성
=> [BE] update: "프로필 수정 profileImage null 일때 등록안함"

client/src/index.tsx, client/src/pages/club/setting/ClubSetting.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 부분: 소모임해체 수정.
=> [FE] 🐛fix : 소모임해체 수정/내부에러페이지 추가

client/src/pages/club/club/EditClub.tsx, client/src/pages/club/intro/ClubIntro.tsx, client/src/pages/user/_receiveOauth2.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [FE] 🐛fix : 카카오톡 로그인 에러 확인 위한 commit

client/src/components/MyPage/ClubListSetting.tsx, client/src/components/MyPage/ClubYes.tsx, client/src/components/home/home/CreateClubImg.tsx, client/src/components/home/home/MainContents.tsx, client/src/pages/mypage/MyPage.tsx
* 요구사항 ID : 
* Issue No. : 
- 마이페이지 로그인 전 get 요청시 오류 뜨는 부분 수정
- 메인-홈 카테고리 삭제(일단 보류!)
=> [FE] 🔧 update: 마이페이지 get요청 오류 수정, 메인-홈 카테고리 삭제

client/src/pages/club/club/CreateClub.tsx
* 요구사항 ID : 
* Issue No. : 
* 소모임 생성 페이지 토큰 추가
=> [FE] 🔧update : 소모임 생성 페이지 토큰 추가

client/src/pages/club/club/CreateClub.tsx, client/src/pages/club/intro/ClubIntro.tsx, client/src/pages/mypage/EditProfile.tsx, client/src/pages/user/_receiveOauth2.tsx
* 요구사항 ID : 
* Issue No. : 
* 소모임 생성 페이지 api 요청 토큰 추가
* 마이페이지 > 프로필 수정 patch api 테스트 완료
* 소모임원 아니면 경기 정보/ 멤버 탭 보이지 않게 처리
=> [FE] 🔧update : api 요청 토큰 추가 및 프로필 수정 api 테스트 완료

client/src/index.tsx, client/src/pages/club/match/ClubSchedule.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/EditMatch.tsx, client/src/pages/club/match/MatchDetail.tsx, client/src/pages/club/member/ClubMember.tsx
* 요구사항 ID : 
* Issue No. : 
* 권한 없는 유저가 소모임 권한이 없을 시 소개페이지로 이동.
=> [FE] 🔧update : 경기관련, 멤버탭 권한제어 추가

client/src/pages/club/member/ClubMember.tsx
=> [FE]🔧 update: 클럽 멤버탭 토큰추가

client/src/pages/mypage/EditProfile.tsx, client/src/pages/mypage/MyPage.tsx
* 요구사항 ID : 
* Issue No. : 
* 프로필 수정 후 마이페이지로 왔을 때 최신 유저 정보 get 요청으로 받아서 렌더링 구현
=> 🔧update : 프로필 수정 최신 user 정보로 뜨게 수정

client/src/components/MyPage/ClubListSetting.tsx, client/src/components/home/home/CreateClubImg.tsx, client/src/components/home/home/MainContents.tsx, client/src/pages/mypage/EditPassword.tsx, client/src/pages/mypage/MyPage.tsx
* 요구사항 ID : 
* Issue No. : 
- 비밀번호 변경 로직 완료
- 현재 비밀번호 틀릴 시 -> 비밀번호가 일치하지 않습니다 알람
- 현재 비밀번호 맞을 시 -> 수정
- 담당한 부분 console.log 삭제
=> [FE] 🔧 update: 비밀번호 변경 로직 완료

server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] update: "프로필 수정 profileImage null 일때 400 에러 테스트"

server/src/main/java/com/codestates/mainproject/group018/somojeon/user/service/UserService.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] update: "프로필 수정 profileImage null 일때 400 에러 테스트 원복"

client/src/components/Header.tsx, client/src/pages/club/intro/ClubIntro.tsx, client/src/pages/mypage/EditProfile.tsx, client/src/pages/user/Login.tsx, client/src/pages/user/_registerModal.tsx
* 요구사항 ID : 
* Issue No. : 
* 프로필 수정 유저 정보 단건조회 api 추가
* 준비되지 않은 서비스 (검색 아이콘, 네이버 로그인 버튼) 화면에서 삭제
* 소모임 소개 페이지에서 undefined 보이던 것 보이지 않게 처리
=> [FE] 🔧update : 프로필 수정 유저 정보 단건 조회 api 추가

server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE] update: "프로필 수정 profileImage null (required = false) 넣어줌"

client/src/pages/club/club/CreateClub.tsx, client/src/pages/club/club/EditClub.tsx, client/src/pages/mypage/EditProfile.tsx, client/src/util/api.ts
* 요구사항 ID : 
* Issue No. : 
* post, patch 후 유저정보 업데이트가 필요한 경우 userinfo 새로 갱신
=> [KE]🔧 update: post, patch 후 userInfo 업데이트 추가구현

client/src/pages/club/intro/ClubIntro.tsx, client/src/pages/mypage/MyPage.tsx
* 요구사항 ID : 
* Issue No. : 
* 전역에서 최신으로 userInfo를 업데이트해주기 때문에 updatedUpserInfo 상태를 만들었던 ClubIntro, MyPage에서 UpdatedUserInfo 상태 관련 코드 제거
=> 🔧update : updatedUserInfo 상태 제거

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/enums/ClubPrivateStatus.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/user/controller/UserController.java
* 요구사항 ID : 
* Issue No. : 
내가 가입한 소모임 리스트 제대로 안되는거 , 소모임 수정을 리더만 할 수 있게 바꿈
* 변경 이유:
* 필요한 경우 작성
=> [BE] update: "소모임 권한 관련 수정 완료"

client/src/components/match/AddMemberPopUp.tsx, client/src/components/match/RecordCard.tsx, client/src/components/match/ScheduleCard.tsx, client/src/components/setting/MemberWaitingCard.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/EditMatch.tsx, client/src/pages/club/match/MatchDetail.tsx, client/src/util/api.ts
* 요구사항 ID : 
* Issue No. : 
* 경기 수정/상세 수정 완료, putFetch 토큰 추가
=> [FE] 🐛 fix: 경기수정/상세 수정, putFetch 토큰 추가

server/src/main/java/com/codestates/mainproject/group018/somojeon/club/controller/ClubController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/dto/ClubDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/entity/Club.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/mapper/ClubMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/club/service/ClubService.java
* 요구사항 ID : 
* Issue No. : 
update: "소모임 공개/비공개 수정완료"
* 변경 이유:
* 필요한 경우 작성
=> [BE] update: "소모임 공개/비공개 수정완료"

client/src/pages/club/setting/ClubSetting.tsx
=> [FE]🐛 fix: 소모임 해체 수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/controller/ScheduleController.java
* 요구사항 ID : 
* Issue No. : 
- [x] Feature 
- schedule delete api 수정
=> [BE] 🔧 update : delete schedule api 수정

client/src/util/authorization/getGlobalState.ts, client/src/util/authorization/useLoginRequestLogic.ts, client/src/util/authorization/useLogoutRequestLogic.ts
* 요구사항 ID : 
* Issue No. : USER-LOGIN
* 브라우저 새로고침 시에도 로그인 상태 유지 (sessionStorage에 정보 저장 후 로그아웃 시 삭제)
=> 🔧update : 새로고침시 로그인 상태 유지

client/src/components/club/member/memberItem.tsx, client/src/components/club/member/recordList.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [FE] 🐛 fix: 승률*100 로직 추가

client/src/components/match/RecordCard.tsx, client/src/components/setting/MemberUserCard.tsx, client/src/pages/club/match/ClubSchedule.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/EditMatch.tsx, client/src/pages/club/match/MatchDetail.tsx, client/src/pages/club/setting/ClubSetting.tsx, client/src/pages/club/setting/MemberSetting.tsx, client/src/pages/club/setting/_totalMember.tsx, client/src/pages/club/setting/_waitingMember.tsx
=> [FE]🐛 fix: 불필요한 코드 정리수정

server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/dto/CandidateDto.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/repository/CandidateRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/candidate/service/CandidateService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/comment/controller/CommentController.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/comment/repository/CommentRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/comment/service/CommentService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/record/mapper/RecordMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/record/service/RecordService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/schedule/service/ScheduleService.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/mapper/TeamMapper.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/repository/TeamRecordRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/repository/TeamRepository.java, server/src/main/java/com/codestates/mainproject/group018/somojeon/team/repository/UserTeamRepository.java
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [BE]💡 comment : 불필요한 import 및 주석 삭제

client/src/util/authorization/useLogoutRequestLogic.ts
* 요구사항 ID : 
* Issue No. : 
* eslint import/no-duplicates 경고 수정
=> [FE] 🐛fix : import/no-duplicates 경고 수정

client/src/pages/club/setting/ClubSetting.tsx, client/src/pages/club/setting/MemberSetting.tsx, client/src/pages/club/setting/_bannedMember.tsx, client/src/pages/mypage/EditProfile.tsx
=> 🐛 fix: 불필요한 코드 삭제

client/src/pages/mypage/DeleteAccount.tsx
=> 🐛 fix: 회원탈퇴시 모달확인, 리더인 소모임 존재시 불가

client/src/pages/club/setting/ClubSetting.tsx, client/src/pages/club/setting/MemberSetting.tsx, client/src/pages/club/setting/_bannedMember.tsx, client/src/pages/mypage/DeleteAccount.tsx, client/src/pages/mypage/EditProfile.tsx
=> [FE]🐛 fix: 회원탈퇴시 모달확인, 리더인 소모임 존재시 불가

client/src/components/setting/MemberUserCard.tsx, client/src/components/setting/MemberWaitingCard.tsx
=> [FE]🚑 HOTFIX: 프로필사진 dummy에서 수정

client/public/index.html, client/src/util/authorization/handleSnsLogin.ts
* 요구사항 ID : 
* Issue No. : 
* SNS 공유시 노출되는 open graph(og) 작성
=> [FE] 🔧update : og 작성

client/public/index.html, client/src/components/match/ScheduleCard.tsx, client/src/index.tsx, client/src/pages/club/match/ClubSchedule.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/_scheduledMatch.tsx
=> [FE] 🐛fix: 지난 일정 참석/불참 노출 삭제, manifest 에러 수정, 에러페이지 intro 에 추가

client/public/index.html
=> [KE]🐛 fix: index.html 문자열 삭제

client/src/components/MyPage/ClubListSetting.tsx, client/src/pages/mypage/MyPage.tsx
* 요구사항 ID : 
* Issue No. : 
* 변경 이유:
* 필요한 경우 작성
=> [FE] 🐛fix : 마이페이지 새로고침시 ServerError 컴포넌트 뜨는 현상 해결

client/src/components/MyPage/ClubListSetting.tsx, client/src/components/MyPage/ClubYes.tsx, client/src/pages/Error/ServerError.tsx, client/src/pages/club/member/MemberList.tsx, client/src/pages/mypage/DeleteAccount.tsx, client/src/pages/mypage/EditProfile.tsx, client/src/pages/mypage/MyPage.tsx
* 요구사항 ID : 
* Issue No. : 
- [] Feature 
* 변경 이유:
* 필요한 경우 작성
=> [FE] 모달 업데이트 수정

client/src/components/match/TeamCard.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/EditMatch.tsx
=> [FE]🔧 update: 기존 기록이 존재할 때 팀구성에 변동이 일어나면 기록 삭제하기 구현 업데이트

client/src/components/match/TeamCard.tsx
=> [FE]🐛 fix: 팀구성 변경시 전적 초기화 관련 멘트 수정

client/src/components/match/AddCandidatePopUp.tsx, client/src/pages/club/match/CreateMatch.tsx, client/src/pages/club/match/MatchDetail.tsx
=> [FE]🐛 fix: 경기일정생성 날짜 에러 수정, 후보자 추가하기 마이너 업데이트
